### ISSUE TITLE
Failed to build wheel for hmmslearn

### ISSUE THREAD

**Issue by steffenhartmeyer** [OxWearables/stepcount#33]
I could not install the package using the normal install routine since pip failed to build the wheel for the hmmslearn v0.2.7 package. I solved this issue by cloning the repo and in setup.py changing the required hmmslearn version to 0.3.0. Then it installed without a problem using `python -m pip install /path/to/package`.

FYI, I am using MacOSX 13.4.1 on a Macbook Pro with the Apple M1 Pro chip.

**Comment by db-2010** [comment]
I run into the same problem since `hmmlearn = 0.2.7` is not natively supported for arm64 architectures like Apple silicon. The first native version is  `hmmlearn = 0.3.0`. 
This will also hinder the installation of [OxWearables/asleep](https://github.com/OxWearables/asleep) package on such architectures. 

Would you consider changing
https://github.com/OxWearables/stepcount/blob/1afed4edaeed1d4b3483c60c0b3d8595198b863b/setup.py#L61

too  `hmmlearn>=0.2.7.` ? 

Thank you very much!

**Comment by chanshing** [comment]
Thanks so much @db-2010 for figuring this out!
